name: Gdrive upload
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Write out README link to src
        run: |
          echo "" >> README.md
          echo "" >> README.md
          echo "Uploaded from commit : `git show -s --oneline`" >> README.md 
          echo "" >> README.md
          echo "To view this commit on GitHub, visit: https://github.com/danya02/rudn-year2-prolog/tree/`git rev-parse HEAD`" >> README.md

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          filename: "*"
          folderId: ${{ secrets.GSA_FOLDER_ID }}
          overwrite: "true" # optional boolean
